// SPDX-License-Identifier: BSD-3-Clause
//
// Copyright (c) 2026, the go-ruby-prawn/prawn authors

// Package prawn is a pure-Go (CGO=0), MRI-faithful reimplementation of Ruby's
// prawn PDF-generation gem.
//
// It mirrors prawn's public DSL — Prawn::Document, its text / font / color /
// graphics / image / table / page-management methods, and the Prawn::Errors
// tree — while writing the actual PDF with the maintained pure-Go
// github.com/go-pdf/fpdf generator. Nothing here shells out to a C PDF library
// or to a Ruby runtime, so the whole module builds and runs with CGO disabled
// on every supported 64-bit target.
//
// # Mapping from Ruby to Go
//
// Ruby's block-form generator
//
//	Prawn::Document.generate("hello.pdf") do |pdf|
//	  pdf.text "Hello World", size: 24, style: :bold
//	  pdf.move_down 20
//	  pdf.stroke_rectangle [0, pdf.cursor], 200, 100
//	end
//
// becomes
//
//	prawn.Generate("hello.pdf", func(pdf *prawn.Document) error {
//	    pdf.Text("Hello World", &prawn.TextOptions{Size: 24, Style: StyleBold})
//	    pdf.MoveDown(20)
//	    pdf.StrokeRectangle(0, pdf.Cursor(), 200, 100)
//	    return nil
//	})
//
// Ruby keyword-argument hashes map to option structs (nil selects prawn's
// defaults); Ruby symbols map to typed Go constants (Style*, Align*, page-size
// and layout string constants). Coordinates use PDF points (1/72 inch) with
// prawn's origin: the lower-left corner of the margin box (the "bounds").
//
// # Verification
//
// Every PDF this package produces is a well-formed PDF 1.3+ document — %PDF-
// header, cross-reference table and trailer — that round-trips through the
// pure-Go rsc.io/pdf reader: the test suite generates documents and parses them
// back to assert page count, the text drawn on each page, the font and size it
// was drawn with, embedded images, and table cells. See prawn_test.go.
//
// # Determinism
//
// The PDF /CreationDate is taken from a package clock seam (see SetClock) rather
// than the wall clock, so output is byte-for-byte reproducible and timezone
// independent. The generated bytes are big-endian/little-endian independent
// (PDF is a byte-oriented format), so output is identical on all six supported
// architectures including s390x.
//
// # Scope
//
// Covered faithfully: document + page management (Generate/New, Render,
// RenderFile, StartNewPage, Cursor, Bounds, MoveDown/MoveUp, Pad), text
// (Text, DrawText, TextBox, Font/FontSize, FillColor/StrokeColor, alignment,
// leading), vector graphics (Rectangle/FillRectangle, Line/StrokeLine,
// Circle/FillCircle, Stroke/Fill, LineWidth), images (PNG/JPEG via Image /
// ImageReader with at/width/height/fit), and a basic Table (column widths,
// header row, cell padding, borders).
//
// Out of scope (documented, not implemented): prawn's advanced inline
// formatting (the formatted-text array / <b><i> inline tags), full flowing
// column text, complex prawn-table features (row/column spanning, per-cell
// styling callbacks, automatic pagination of tables), embedded TTF/OTF fonts
// (only the 14 standard PDF/AFM fonts are offered), and SVG. These are noted
// here so the surface's boundaries are explicit.
package prawn
